name: CD prod

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
