name: CD prod

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
