name: CD prod

on:
  push:
    paths-ignore::
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/*'
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Init slack notif
